### ISSUE TITLE
Brak edycji wiadomości po wykorzystaniu kuponu

### ISSUE THREAD

**Issue by stanislaw-piechota** [michkied/PoliKupon#1]
Po wykorzystaniu kuponu bot nie edytował wiadomości.
Według mnie coś może tkwić w innych reakcjach.

Pod spodem obrazy:
(1) - typowe zachowanie bota (1 emotikona)
(2) - brak edycji (wiele różnych emotikon)
![obraz](https://user-images.githubusercontent.com/43549663/100209568-53615c00-2f0a-11eb-8a12-67d213fee360.png)

Nie powoduje to jakichś znaczących utrudnień, ale bywa mylące ;)

**Comment by michkied** [comment]
Dzięki za zgłoszenie, sprawdzę w wolnej chwili

**Comment by michkied** [comment]
Nie udało mi się odtworzyć błędu, więc raczej nie chodziło o emotikony. Wydaje mi się natomiast, że znalazłem prawdziwą przyczynę problemu - bot wysyłał do API informację o edycji dwa razy (w wyniku brakującego warunku). Przez to, że były one wysyłane bardzo szybko po sobie, polecenia mogły się nakładać lub zmieniać kolejność. Ciężko odtworzyć tę sytuację i sprawdzić czy rzeczywiście o to chodzi, ale spotkałem się już z takimi błędami, więc podejrzewam że to to.
Commit **v1.0.24** dodaje brakujący warunek, więc wszystko powinno już działać.

Dzięki wielkie za zwrócenie uwagi! 💙
